# -*- coding: utf-8 -*-
"""GitHub 上传用的本地配置模板。

复制为 `local_settings.py` 后，再按本机环境填写真实路径和密钥。
"""
from __future__ import annotations

from pathlib import Path


RUN_MODE = "integrated_supervisor"  # integrated_supervisor / research_only / release_only / execution_only / full_cycle / industry_router_only
DEFAULT_RUN_PROFILE = "quick_test"  # overnight / daily_production / quick_test
LOOKBACK_HOURS = 24
DOWNLOAD_HIGH_VALUE_PDF = True
MAX_PDF_FETCH_PER_RUN = 12
MAX_PRIORITY_EVENTS = 12
MAX_CNINFO_PAGES_PER_MARKET = 3
ENABLE_CNINFO = True
ENABLE_SSE = True
ENABLE_SZSE = True
ENABLE_TUSHARE_NEWS = True
ENABLE_TUSHARE_MAJOR_NEWS = True
TUSHARE_NEWS_SOURCES = ["sina", "cls", "wallstreetcn"]
TUSHARE_MAJOR_NEWS_SOURCES = ["新浪财经", "华尔街见闻", "财联社"]
TUSHARE_NEWS_MAX_SOURCES_PER_RUN = 1
TUSHARE_MAJOR_NEWS_MAX_SOURCES_PER_RUN = 3
TUSHARE_NEWS_RATE_WINDOW_SECONDS = 60
TUSHARE_NEWS_RATE_MAX_CALLS = 1
TUSHARE_MAJOR_NEWS_RATE_WINDOW_SECONDS = 3600
TUSHARE_MAJOR_NEWS_RATE_MAX_CALLS = 4
ENABLE_OPENAI_RESEARCH = True
ENABLE_DEEPSEEK_WORKER = True
ENABLE_LOCAL_OLLAMA_RESEARCH = True
ENABLE_MARKET_PIPELINE = True
ENABLE_EXECUTION_BRIDGE = False
ENABLE_DAILY_STRATEGY_FEEDBACK = True
ENABLE_INDUSTRY_ROUTER = True
ENABLE_MARKET_STATE_ENGINE = True
ENABLE_TECHNICAL_CONFIRMATION = True

MAX_EVENTS_PER_RUN = 18
DEEPSEEK_BATCH_SIZE = 6
LLM_MIN_EVENT_SCORE = 1.35
MAX_CONTENT_CHARS_PER_EVENT = 1800
SAVE_EXTRACT_SUMMARY = True

TOKEN_PLAN_MIN_INTERVAL_HOURS = 24
SUPERVISOR_RUN_FOREVER = False
SUPERVISOR_MAX_TICKS = 1
SUPERVISOR_SLEEP_SECONDS = 300
V5_GPU_MAX_CYCLES_PER_TICK = 8
V5_GPU_DRY_RUN = False
REQUIRE_GPU = True
STRATEGY_FEEDBACK_LOOKBACK_DAYS = 5
DEFENSIVE_DAILY_RETURN_THRESHOLD = -0.02
DEFENSIVE_THREE_DAY_RETURN_THRESHOLD = -0.03
AGGRESSIVE_DAILY_RETURN_THRESHOLD = 0.015
AGGRESSIVE_THREE_DAY_RETURN_THRESHOLD = 0.02

OVERNIGHT_V5_GPU_MAX_CYCLES_PER_TICK = 8
OVERNIGHT_TOKEN_PLAN_MIN_INTERVAL_HOURS = 24
OVERNIGHT_MAX_PDF_FETCH_PER_RUN = 12
OVERNIGHT_MAX_EVENTS_PER_RUN = 18
OVERNIGHT_DEEPSEEK_BATCH_SIZE = 6
OVERNIGHT_MAX_PRIORITY_EVENTS = 12

QUICK_TEST_V5_GPU_MAX_CYCLES_PER_TICK = 1
QUICK_TEST_TOKEN_PLAN_MIN_INTERVAL_HOURS = 24
QUICK_TEST_MAX_PDF_FETCH_PER_RUN = 2
QUICK_TEST_MAX_EVENTS_PER_RUN = 6
QUICK_TEST_DEEPSEEK_BATCH_SIZE = 2
QUICK_TEST_MAX_PRIORITY_EVENTS = 4

DAILY_PRODUCTION_V5_GPU_MAX_CYCLES_PER_TICK = 3
DAILY_PRODUCTION_TOKEN_PLAN_MIN_INTERVAL_HOURS = 24
DAILY_PRODUCTION_MAX_PDF_FETCH_PER_RUN = 6
DAILY_PRODUCTION_MAX_EVENTS_PER_RUN = 12
DAILY_PRODUCTION_DEEPSEEK_BATCH_SIZE = 4
DAILY_PRODUCTION_MAX_PRIORITY_EVENTS = 8

INDUSTRY_ROUTER_HISTORY_LOOKBACK_DAYS = 14
INDUSTRY_ROUTER_ENABLE_BACKTEST = True
INDUSTRY_ROUTER_BACKTEST_HORIZONS = [1, 2]
INDUSTRY_ROUTER_BACKTEST_TOP_K = 3
INDUSTRY_ROUTER_ENABLE_CONTEXT_PACK = True
INDUSTRY_ROUTER_ENABLE_SOURCE_FETCH = True
INDUSTRY_ROUTER_SOURCE_FETCH_TIMEOUT_SECONDS = 8
INDUSTRY_ROUTER_SOURCE_FETCH_CACHE_HOURS = 12
INDUSTRY_ROUTER_SOURCE_FETCH_MAX_SOURCES_PER_RUN = 9
MARKET_STATE_USE_ROUTER_BIAS = True
PORTFOLIO_MARKET_STATE_AWARE_SIZING = True
PORTFOLIO_TECHNICAL_CONFIRMATION_GATE = True

ENABLE_PORTFOLIO_RECOMMENDATION = True
PORTFOLIO_MAX_NAMES = 20
PORTFOLIO_SINGLE_NAME_CAP = 0.10
PORTFOLIO_TOTAL_EXPOSURE_CAP = 1.00
PORTFOLIO_SIMULATION_READY_NEED_GATE = False
PORTFOLIO_ENABLE_POST_FILTER_REWEIGHT = True
PORTFOLIO_MIN_EXPOSURE_FILL_RATIO = 0.75
PORTFOLIO_ENFORCE_EXECUTABLE_UNIVERSE = True
PORTFOLIO_EXECUTABLE_ALLOWED_SUFFIXES = [".SH", ".SZ"]
PORTFOLIO_EXECUTABLE_REQUIRE_TRADABLE_BASIC = True
ENABLE_PORTFOLIO_V2A = True
PORTFOLIO_ENABLE_LIFECYCLE_STATE_MACHINE = True
PORTFOLIO_ENABLE_ADMISSION_REPLACEMENT = True
PORTFOLIO_ENABLE_SOFT_CROWDING_PENALTY = True
PORTFOLIO_ENABLE_RICH_PORTFOLIO_AUDIT = True
PORTFOLIO_V2A_PILOT_MAX_WEIGHT = 0.04
PORTFOLIO_V2A_BUILD_SPEED = 1.25
PORTFOLIO_V2A_TRIM_SPEED = 0.72
PORTFOLIO_V2A_REPLACEMENT_IMPROVEMENT_THRESHOLD = 0.08
PORTFOLIO_V2A_SOFT_CROWDING_PENALTY_STRENGTH = 0.08
ENABLE_PORTFOLIO_CONTROL = True
PORTFOLIO_CONTROL_DRIFT_THRESHOLD = 0.005
PORTFOLIO_CONTROL_MAX_DAILY_TURNOVER_RATIO = 0.25
PORTFOLIO_CONTROL_ENABLE_EXECUTION_FEEDBACK = True
PORTFOLIO_CONTROL_ENABLE_DEV_LOG_SNAPSHOT = True
PORTFOLIO_CONTROL_DEV_LOG_TOP_HOLDINGS = 8
PORTFOLIO_CONTROL_ALLOW_ODD_LOT_EXIT = True
ENABLE_OMS = True
OMS_USE_BROKER_TRUTH_FOR_V2A_CONTINUITY = True
OMS_INTENT_EXPIRY_DAYS = 3
OMS_CONTROL_FEEDBACK_LOOKBACK_RUNS = 20
OMS_RESEARCH_META_LOOKBACK_RUNS = 60
OMS_COMPAT_WRITE_LATEST_ACCOUNT_STATE = True
OMS_ENABLE_BROKER_CANCEL = True
EXECUTION_ACCOUNT_MODE = "precision"  # simulation / precision
PRECISION_TRADE_ENABLED = False
ALLOW_INTEGRATED_PRECISION_EXECUTION = False
EXECUTION_IGNORE_MARKET_PANIC_REDUCE_ONLY = False
EXECUTION_ALLOW_UNFINISHED_ORDERS_RECONCILE = False
ENABLE_TRADE_RELEASE = True
TRADE_RELEASE_VALID_AFTER_TIME = "09:30:30"
TRADE_RELEASE_EXPIRES_AT_TIME = "15:00:00"
TRADE_RELEASE_CALENDAR_LOOKBACK_DAYS = 7
TRADE_RELEASE_CALENDAR_FORWARD_DAYS = 45
ENABLE_TRADE_CLOCK = True
TRADE_CLOCK_TIMEZONE = "Asia/Shanghai"
TRADE_CLOCK_POLL_SECONDS = 30
TRADE_CLOCK_EXECUTION_WINDOWS = [
    {"label": "morning_primary", "start": "09:30:30", "end": "10:00:00"},
    {"label": "afternoon_primary", "start": "13:00:00", "end": "14:50:00"},
]
TRADE_CLOCK_SCHEDULER_ENABLED = True
TRADE_CLOCK_SCHEDULER_PROFILE = "daily_production"
TRADE_CLOCK_SCHEDULER_LOG_TAIL_LINES = 30
TRADE_CLOCK_PHASE_RESEARCH_TIME = "15:05:00"
TRADE_CLOCK_PHASE_RELEASE_TIME = "15:10:00"
TRADE_CLOCK_PHASE_PREOPEN_GATE_TIME = "09:20:00"
TRADE_CLOCK_PHASE_SIMULATION_TIME = "09:30:35"
TRADE_CLOCK_PHASE_SHADOW_TIME = "09:35:00"
TRADE_CLOCK_PHASE_MIDDAY_REVIEW_TIME = "11:35:00"
TRADE_CLOCK_PHASE_AFTERNOON_EXECUTION_TIME = "13:05:00"
TRADE_CLOCK_PHASE_AFTERNOON_SHADOW_TIME = "13:15:00"
TRADE_CLOCK_PHASE_SUMMARY_TIME = "15:20:00"
TRADE_CLOCK_RESEARCH_TIMEOUT_MINUTES = 420
TRADE_CLOCK_RELEASE_TIMEOUT_MINUTES = 30
TRADE_CLOCK_PREOPEN_GATE_TIMEOUT_MINUTES = 15
TRADE_CLOCK_SIMULATION_TIMEOUT_MINUTES = 45
TRADE_CLOCK_SHADOW_TIMEOUT_MINUTES = 30
TRADE_CLOCK_MIDDAY_REVIEW_TIMEOUT_MINUTES = 10
TRADE_CLOCK_AFTERNOON_EXECUTION_TIMEOUT_MINUTES = 30
TRADE_CLOCK_AFTERNOON_SHADOW_TIMEOUT_MINUTES = 20
TRADE_CLOCK_SUMMARY_TIMEOUT_MINUTES = 20
TRADE_CLOCK_FALLBACK_MAX_PORTFOLIO_AGE_HOURS = 96
TRADE_CLOCK_FALLBACK_REQUIRE_RELEASE = False
TRADE_CLOCK_SIMULATION_NAMESPACE = "simulation"
TRADE_CLOCK_SHADOW_NAMESPACE = "shadow"
TRADE_CLOCK_SHADOW_ENABLED = False
TRADE_CLOCK_AFTERNOON_SHADOW_ENABLED = False
TRADE_CLOCK_SIMULATION_EXECUTION_MODE = "precision"
TRADE_CLOCK_SHADOW_EXECUTION_MODE = "precision"
TRADE_CLOCK_SIMULATION_PRECISION_TRADE = True
TRADE_CLOCK_SHADOW_PRECISION_TRADE = True
TRADE_CLOCK_SIMULATION_IGNORE_MARKET_PANIC_REDUCE_ONLY = True
TRADE_CLOCK_SHADOW_IGNORE_MARKET_PANIC_REDUCE_ONLY = True
TRADE_CLOCK_SIMULATION_ALLOW_UNFINISHED_ORDERS_RECONCILE = False
TRADE_CLOCK_SHADOW_ALLOW_UNFINISHED_ORDERS_RECONCILE = False
ENABLE_SAFETY_LAYER = True
SAFETY_HEALTH_PROBE_INTERVAL_SECONDS = 300
SAFETY_ACCOUNT_STATE_MAX_AGE_SECONDS = 900
SAFETY_POSITION_SYNC_MAX_AGE_SECONDS = 900
SAFETY_RELEASE_MAX_AGE_SECONDS = 172800
SAFETY_FAIL_ON_UNFINISHED_ORDERS = True
SAFETY_FAIL_ON_UNKNOWN_ORDER_STATUS = True
SAFETY_DEGRADED_REDUCE_ONLY = True
SAFETY_CAUTION_TURNOVER_MULTIPLIER = 0.5
SAFETY_CAUTION_MARKET_MEAN_PCT_CHG = -1.0
SAFETY_PANIC_MARKET_MEAN_PCT_CHG = -2.2
SAFETY_CAUTION_HS300_RETURN_PCT = -1.5
SAFETY_PANIC_HS300_RETURN_PCT = -3.0
SAFETY_CAUTION_LIMIT_DOWN_RATIO = 0.05
SAFETY_PANIC_LIMIT_DOWN_RATIO = 0.12
SAFETY_EXECUTION_FAIL_RATIO_DEGRADED = 0.35
SAFETY_EXECUTION_FAIL_RATIO_HALT = 0.75
SAFETY_EXECUTION_FAIL_MIN_ORDERS = 3

HIGH_VALUE_TITLE_KEYWORDS = [
    "业绩预告", "业绩快报", "年度报告", "半年度报告", "一季度报告", "三季度报告",
    "回购", "分红", "权益分派", "增持", "减持", "定向增发", "发行股份", "可转债",
    "并购", "重组", "重大合同", "中标", "停牌", "复牌", "风险提示", "问询函", "处罚",
    "诉讼", "仲裁", "要约收购", "股份解除限售",
]

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = PACKAGE_ROOT.parents[1]
DATA_ROOT = REPO_ROOT / "data"

PORTFOLIO_OUTPUT_ROOT = str(DATA_ROOT / "portfolio_recommendation_v6")
TRAIN_TABLE_DIR = str(DATA_ROOT / "ml_datasets" / "train_table_v1")
HUB_OUTPUT_ROOT = str(DATA_ROOT / "ml_runs" / "research_hub_v6")
RAW_EVENT_ROOT = str(DATA_ROOT / "event_lake_v6" / "raw")
EVENT_STORE_ROOT = str(DATA_ROOT / "event_lake_v6" / "curated")
INVENTORY_ROOT = str(DATA_ROOT / "event_lake_v6" / "inventory")
RESEARCH_ROOT = str(DATA_ROOT / "event_lake_v6" / "research")
BRIDGE_ROOT = str(DATA_ROOT / "event_lake_v6" / "bridge")
MARKET_STATE_ROOT = str(DATA_ROOT / "market_state_v6")
DAILY_CACHE_ROOT = str(DATA_ROOT / "daily_cache_v6")
LOG_ROOT = str(DATA_ROOT / "event_lake_v6" / "logs")
ENRICHED_DAILY_DIR = str(DATA_ROOT / "enriched_daily_csv_qfq")
TRADABILITY_FLAGS_PATH = str(DATA_ROOT / "auxiliary_data" / "tradability_flags.csv")
HS300_DAILY_PATH = str(DATA_ROOT / "index_daily_csv" / "000300_HS300.csv")
HS300_MEMBERSHIP_HISTORY_PATH = str(DATA_ROOT / "auxiliary_data" / "hs300_membership_history.csv")
LISTING_MASTER_PATH = str(DATA_ROOT / "auxiliary_data" / "listing_date_master.csv")
STOCK_UNIVERSE_CLEAN_PATH = str(DATA_ROOT / "auxiliary_data" / "stock_universe_clean.csv")
LIVE_EXECUTION_ROOT = str(DATA_ROOT / "live_execution_bridge")
LIVE_PRICE_SNAPSHOT_PATH = str(DATA_ROOT / "live_execution_bridge" / "daily_price_snapshot.csv")
TRADE_RELEASE_ROOT = str(DATA_ROOT / "trade_release_v1")
TRADE_CLOCK_ROOT = str(DATA_ROOT / "trade_clock")
AUTOMATION_RUNS_ROOT = str(REPO_ROOT / "outputs" / "automation_runs")
TRADING_CALENDAR_CACHE_PATH = str(DATA_ROOT / "market_state_v6" / "trading_calendar_a_share.csv")
INDUSTRY_ROUTER_OUTPUT_ROOT = str(Path(RESEARCH_ROOT) / "industry_router")
TECHNICAL_CONFIRMATION_ROOT = str(Path(RESEARCH_ROOT) / "technical_confirmation")
OMS_OUTPUT_ROOT = str(Path(LIVE_EXECUTION_ROOT) / "oms_v1")
TRAIN_APPEND_LOOKBACK_ROWS = 160
TRAIN_APPEND_PREFIX = "part_live_append"
SYNC_TUSHARE_MISSING_DAYS = True

PYTHON_EXECUTABLE = r"C:\path\to\your\python.exe"
V5_PROJECT_ROOT = str(REPO_ROOT / "quant_research_hub_v5_1_gpu_integrated")
V5_HUB_OUTPUT_ROOT = str(DATA_ROOT / "research_hub_v5_1_gpu_integrated")
V5_BRIDGE_INPUT_ROOT = BRIDGE_ROOT
GMTRADE_PYTHON_EXECUTABLE = r"C:\path\to\gmtrade39\Scripts\python.exe"
GMTRADE_RUNTIME_CONFIG_TEMPLATE = str(PACKAGE_ROOT / "configs" / "gmtrade_runtime_config.example.json")
GMTRADE_RUNTIME_AUTOGEN_PATH = str(PACKAGE_ROOT / "configs" / "gmtrade_runtime_config.autogen.json")
GMTRADE_BRIDGE_SCRIPT_PATH = str(PACKAGE_ROOT / "run_gmtrade_portfolio_bridge.py")
GMTRADE_HEALTH_PROBE_SCRIPT_PATH = str(PACKAGE_ROOT / "run_gmtrade_health_probe.py")
INDUSTRY_ROUTER_CONTRACT_ROOT = str(PACKAGE_ROOT / "configs" / "industry_router")
MARKET_STATE_CONFIG_PATH = str(PACKAGE_ROOT / "configs" / "market_state" / "default.json")
TECHNICAL_CONFIRMATION_CONFIG_PATH = str(PACKAGE_ROOT / "configs" / "technical_confirmation" / "default.json")

OPENAI_MODEL = "gpt-5.4"
OPENAI_RESEARCH_FALLBACK_MODELS = ["gpt-4.1", "gpt-4o"]
DEEPSEEK_MODEL = "deepseek-chat"
DEEPSEEK_RESEARCH_FALLBACK_MODELS = ["deepseek-chat", "deepseek-reasoner"]
OPENAI_BASE_URL = "https://api.openai.com/v1"
DEEPSEEK_BASE_URL = "https://api.deepseek.com"
TUSHARE_TOKEN_ENV = "TUSHARE_TOKEN"
TUSHARE_TOKEN = ""
OPENAI_API_KEY_ENV = "OPENAI_API_KEY"
DEEPSEEK_API_KEY_ENV = "DEEPSEEK_API_KEY"

OLLAMA_BASE_URL = "http://localhost:11434"
OLLAMA_MODEL = "qwen2.5:7b"  # legacy shared default
OLLAMA_TIMEOUT_SECONDS = 120  # legacy shared default
OLLAMA_EVENT_EXTRACT_MODEL = "qwen2.5:7b"
OLLAMA_EVENT_EXTRACT_TIMEOUT_SECONDS = 120
OLLAMA_RESEARCH_MODEL = "deepseek-r1:14b"
OLLAMA_RESEARCH_FALLBACK_MODELS = ["deepseek-r1:14b", "qwen2.5:7b"]
OLLAMA_RESEARCH_TIMEOUT_SECONDS = 180
ENABLE_LOCAL_OLLAMA_EVIDENCE_CARD = True
OLLAMA_EVIDENCE_CARD_MODEL = "deepseek-r1:14b"
OLLAMA_EVIDENCE_CARD_TIMEOUT_SECONDS = 180
OLLAMA_EVIDENCE_CARD_MAX_ITEMS = 2
ENABLE_LOCAL_OLLAMA_REVIEW_ROUTER = True
OLLAMA_REVIEW_ROUTER_MODEL = "qwen2.5:7b"
OLLAMA_REVIEW_ROUTER_TIMEOUT_SECONDS = 90
OLLAMA_REVIEW_ROUTER_MAX_ITEMS = 6
ENABLE_LOCAL_OLLAMA_RUNTIME_EXPLAINER = True
OLLAMA_RUNTIME_EXPLAINER_MODEL = "qwen2.5:7b"
OLLAMA_RUNTIME_EXPLAINER_TIMEOUT_SECONDS = 45
OLLAMA_RUNTIME_EXPLAINER_STAGES = ["v6_planning", "v5_gpu", "portfolio_recommendation", "execution_bridge"]
ENABLE_LOCAL_OLLAMA_V5_REVIEW = True
OLLAMA_V5_REVIEW_MODEL = "deepseek-r1:14b"
OLLAMA_V5_REVIEW_TIMEOUT_SECONDS = 180
